M48
; DRILL file {KiCad 8.0.6} date 2025-01-20T01:56:26+0100
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-01-20T01:56:26+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.520
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.770
%
G90
G05
T1
X142.45Y-91.95
T2
X142.45Y-84.45
M30
